### PR TITLE
Multiple classifications 20

### LINKED ISSUE #20: Multiple classifications
Spicedham needs to be able to classify multiple different types of input, such as _abuse_ and _spam_.
One approach would be to add an additional field to the public API and the database:
In `spicedham/__init__.py`:

``` python
def train(input_type, training_data, match):
    ...
def classify(input_type, classification_data):
    ...
```

In use:

``` python
sh = Spicedham({'config': 'vars'})
train('spam', ['SPAMY', 'STUFF'], True)
train('abuse', ['abusive', 'things', True)
#etc.
```

### PR DESCRIPTION
**Pull request by iankronquist**
Fixes #20.

### CODE REVIEW

**Comment by iankronquist** [comment]
@willkg r?

**Comment by willkg** [comment]
I get a bunch of test errors like this:

```
======================================================================
ERROR: test_classify (tests.test_bayes.TestBayes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willkg/mozilla/spicedham/tests/test_bayes.py", line 15, in test_classify
    self._training(classification_type, b)
  File "/home/willkg/mozilla/spicedham/tests/test_bayes.py", line 38, in _training
    bayes.train(classification_type, message, is_spam)
  File "/home/willkg/mozilla/spicedham/spicedham/bayes.py", line 37, in train
    {'numSpam': 0, 'numTotal': 0})
  File "/home/willkg/mozilla/spicedham/spicedham/sqlalchemywrapper/__init__.py", line 40, in get_key
    store = query.one()
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2369, in one
    ret = list(self)
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/home/willkg/.virtualenvs/spicedham/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such column: store.classification_type u'SELECT store."key" AS store_key, store.classifier AS store_classifier, store.classification_type AS store_classification_type, store.value AS store_value \nFROM store \nWHERE store.classifier = ? AND store.classification_type = ? AND store."key" = ?' ('Bayes', 'type', '*')
```

I'm guessing the test harness isn't starting with a clean db for sqlalchemy or isn't setting it up right or something.

Any ideas?

**Comment by iankronquist** [comment]
Delete the database ('./db.sqlite' or './spicedham.db' or something
similar). The classification_type column isn't in that DB, I just added
it in that PR.
You wanted the database to save to the filesystem by default, as opposed
to staying in memory, so obviously it doesn't clean up.

**Comment by willkg** [comment]
Sounds like the test harness should get fixed to use an in-memory database or to use a database on the file system that's clean and temporary.

**Comment by iankronquist** [comment]
@willkg specifies a default config for various tests.

**Comment by iankronquist** [comment]
@willkg refactor tests.

**Comment by willkg** [comment]
That looks much better. Good job! r+

**Pull request merged**
